name: Tinybird - CD Workflow

on:
  workflow_dispatch:
  push:
    paths:
      - 'tinybird/**'
    branches:
      - main
jobs:
  cd:
    uses: tinybirdco/ci/.github/workflows/cd.yml@v4.1.0
    with:
      data_project_dir: ./tinybird
    secrets:
      tb_admin_token: 
      tb_host: ${{ secrets.TB_HOST }}
