  name: Tinybird - CI Workflow

  on:
    workflow_dispatch:
    pull_request:
      paths:
        - 'tinybird/**'
      branches:
        - main
      types: [opened, reopened, labeled, unlabeled, synchronize, closed]

  concurrency: ${{ github.workflow }}-${{ github.event.pull_request.number }}

  jobs:
      ci:
        uses: tinybirdco/ci/.github/workflows/ci.yml@v4.1.0
        with:
          data_project_dir: ./tinybird
        secrets:
          tb_admin_token: "p.eyJ1IjogIjUxMTk2MzNmLTIyNzItNDljMS1hZDAzLTI1NmQyYzZlNzI2MiIsICJpZCI6ICI2OGJhMWJhYy1mZjY1LTQ2ZWUtYTU1OC00NWUwMjQ4MmYwMjUiLCAiaG9zdCI6ICJhd3MtdXMtd2VzdC0yIn0.3dIApf2uUPwJ_9jlJqw5w7KiNgZzuj8ZJXIJzoVCRu4"
          tb_host: "https://api.tinybird.co"